WCONINJE
'INJECT1'	'WAT'	'OPEN'	'BHP' 1* 500 /
'INJECT2'	'WAT'	'OPEN'	'BHP' 1* 2000 /
'INJECT3'	'WAT'	'OPEN'	'BHP' 1* 500 /
'INJECT4'	'WAT'	'OPEN'	'BHP' 1* 1600 /
'INJECT5'	'WAT'	'OPEN'	'BHP' 1* 1600 /
/

RPTSCHED
'WELLS=2'    'WELSPECS'    'CPU=2'     'FIP=2'                        /

DATES
1  FEB   2011  /
1  MAY  2011  /
1  AUG  2011  /
1  NOV  2011  /
1  FEB  2012  /
1  MAY  2012  /
1  AUG  2012  /
1  NOV  2012  /
1  FEB   2013  /
1  MAY  2013  /
1  AUG  2013  /
1  NOV  2013  /
1  FEB   2014  /
1  MAY  2014  /
1  AUG  2014  /
1  NOV  2014  /
1  FEB   2015  /
1  MAY  2015  /
1  AUG  2015  /
1  NOV  2015  /
1  FEB   2016  /
1  MAY  2016  /
1  AUG  2016  /
1  NOV  2016  /
1  FEB   2017  /
1  MAY  2017  /
1  AUG  2017  /
1  NOV  2017  /
1  FEB   2018  /
1  MAY  2018  /
1  AUG  2018  /
1  NOV  2018  /
1  FEB   2019  /
1  MAY  2019  /
1  AUG  2019  /
1  NOV  2019  /

/
END